language: nix
sudo: required
os:
- linux
env:
  global:
    - NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
install:
- sudo mount -o remount,exec,size=4G,mode=755 /run/user || true
- nix-env -iA nixpkgs.nix-prefetch-git nixpkgs.nix-prefetch-hg
script:
- nix-shell nix/shell.nix --run 'python3 build.py html'
