name: "CI"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: csound-flossmanual
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: |
       nix-build shell.nix
       PATH=$PATH:$(pwd)/result/bin
       yarn && yarn build
       yarn build:pdf
       mv *.pdf public
