name: "CI"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: csound-flossmanual
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Install build dependencies from cache
      run: |
        nix-env -i -f shell.nix
        mkdir -p $HOME/.local/share/fonts
        cp -rf $(nix-build --no-out-link '<nixpkgs>' -A fira)/share/fonts/* \
          $HOME/.local/share/fonts
        fc-cache -f -v
    - name: Install npm dependencies via yarn
      run: yarn
    - name: Build the book website
      run: yarn build
    - name: Build the pdf
      run: yarn build:pdf && mv *.pdf public
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: public
        path: ./public/
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
